inherit_from: .rubocop_todo.yml

Style/Documentation:
  Enabled: false

AllCops:
  NewCops: enable
  SuggestExtensions: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Exclude:
    - 'lib/bricklink_api_wrapper/user_inventory.rb'

Style/NumericLiterals:
  Exclude:
    - 'spec/**/*'
